# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 03:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('link', models.CharField(max_length=64, verbose_name='订阅源')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('link', models.CharField(max_length=64, verbose_name='链接')),
                ('pubdate', models.CharField(max_length=32, verbose_name='发布时间')),
                ('description', models.CharField(max_length=128, verbose_name='描述')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Channel', verbose_name='所属源')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='channel',
            field=models.ManyToManyField(to='Main.Channel', verbose_name='订阅收藏'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
