# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_channel_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
