# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20161206_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pubdate',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
