# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20161207_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pubdate']},
        ),
        migrations.AlterField(
            model_name='item',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
    ]
