# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20161210_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
    ]
