# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20170103_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
    ]
